
export const COUNTRIES = [
  { name: "Afghanistan", code: "af", lat: 33.93, lng: 67.71, languages: ["Pashto", "Dari"], facts: ["National game is Buzkashi.", "World's largest producer of opium.", "New Year is celebrated in March."], shapeDescription: "A leaf shape with a stem (Wakhan Corridor) pointing northeast." },
  { name: "Albania", code: "al", lat: 41.15, lng: 20.16, languages: ["Albanian"], facts: ["Has over 170,000 bunkers.", "Mother Teresa was Albanian.", "Nodding means no here."], shapeDescription: "A narrow strip on the Balkan coast." },
  { name: "Algeria", code: "dz", lat: 28.03, lng: 1.65, languages: ["Arabic"], facts: ["Largest country in Africa.", "Sahara covers 80% of land.", "Home to the fennec fox."], shapeDescription: "A large four-sided shape in North Africa." },
  { name: "Andorra", code: "ad", lat: 42.50, lng: 1.52, languages: ["Catalan"], facts: ["Co-principality ruled by two princes.", "Has no airport.", "Life expectancy is very high."], shapeDescription: "Tiny mountainous triangle between France and Spain." },
  { name: "Angola", code: "ao", lat: -11.20, lng: 17.87, languages: ["Portuguese"], facts: ["Kizomba music originated here.", "Giant Sable Antelope is national symbol.", "Capital Luanda is very expensive."], shapeDescription: "Roughly square shape on the west coast of Africa." },
  { name: "Argentina", code: "ar", lat: -38.41, lng: -63.61, languages: ["Spanish"], facts: ["Birthplace of Tango.", "Highest peak in Americas.", "Name means 'Land of Silver'."], shapeDescription: "A long wedge tapering south." },
  { name: "Armenia", code: "am", lat: 40.06, lng: 45.03, languages: ["Armenian"], facts: ["First country to adopt Christianity.", "Chess is compulsory in schools.", "Mount Ararat is a national symbol."], shapeDescription: "Landlocked, oval-shaped in the Caucasus." },
  { name: "Australia", code: "au", lat: -25.27, lng: 133.77, languages: ["English"], facts: ["Home to Great Barrier Reef.", "More kangaroos than people.", "A continent and a country."], shapeDescription: "Massive island with a bite taken out of the bottom." },
  { name: "Austria", code: "at", lat: 47.51, lng: 14.55, languages: ["German"], facts: ["Home to oldest zoo.", "Arnold Schwarzenegger born here.", "Sewing machine invented here."], shapeDescription: "Guitar or violin shape in Central Europe." },
  { name: "Azerbaijan", code: "az", lat: 40.14, lng: 47.57, languages: ["Azerbaijani"], facts: ["Land of Fire.", "Capital lies below sea level.", "Tea is the national drink."], shapeDescription: "Bird-shaped, flying towards the Caspian Sea." },
  { name: "Bahamas", code: "bs", lat: 25.03, lng: -77.39, languages: ["English"], facts: ["Has swimming pigs.", "Astronauts love the view of it.", "Site of Columbus's first landing."], shapeDescription: "Archipelago of 700 islands." },
  { name: "Bahrain", code: "bh", lat: 26.06, lng: 50.55, languages: ["Arabic"], facts: ["Home to the Tree of Life.", "Used to be a pearl center.", "Connected to Saudi Arabia by bridge."], shapeDescription: "Small archipelago in the Persian Gulf." },
  { name: "Bangladesh", code: "bd", lat: 23.68, lng: 90.35, languages: ["Bengali"], facts: ["Home to Sundarbans mangroves.", "National game is Kabaddi.", "Has 6 seasons."], shapeDescription: "Delta shape almost surrounded by India." },
  { name: "Belgium", code: "be", lat: 50.50, lng: 4.46, languages: ["Dutch", "French"], facts: ["Famous for chocolate.", "Invented the saxophone.", "HQ of EU and NATO."], shapeDescription: "Small triangle in Western Europe." },
  { name: "Belize", code: "bz", lat: 17.18, lng: -88.49, languages: ["English"], facts: ["Great Blue Hole is here.", "Only Jaguar preserve.", "Former British Honduras."], shapeDescription: "Rectangular cut out of Guatemala's side." },
  { name: "Bhutan", code: "bt", lat: 27.51, lng: 90.43, languages: ["Dzongkha"], facts: ["Measures Gross National Happiness.", "No traffic lights.", "Banned tobacco."], shapeDescription: "Small landlocked buffer in Himalayas." },
  { name: "Bolivia", code: "bo", lat: -16.29, lng: -63.58, languages: ["Spanish"], facts: ["Has pink dolphins.", "Salt Flats (Salar de Uyuni).", "Capital is highest in world."], shapeDescription: "Landlocked heart of South America." },
  { name: "Bosnia and Herzegovina", code: "ba", lat: 43.91, lng: 17.67, languages: ["Bosnian"], facts: ["Sarajevo hosted 1984 Olympics.", "Called 'Heart Shaped Land'.", "Stari Most bridge is iconic."], shapeDescription: "Heart-shaped with a tiny coast." },
  { name: "Botswana", code: "bw", lat: -22.32, lng: 24.68, languages: ["English", "Tswana"], facts: ["Home to Okavango Delta.", "World's largest diamond producer.", "Oldest democracy in Africa."], shapeDescription: "Landlocked flat tableland." },
  { name: "Brazil", code: "br", lat: -14.23, lng: -51.92, languages: ["Portuguese"], facts: ["Amazon Rainforest.", "Largest coffee producer.", "Rio Carnival."], shapeDescription: "Massive diamond shape in South America." },
  { name: "Bulgaria", code: "bg", lat: 42.73, lng: 25.48, languages: ["Bulgarian"], facts: ["Invented Cyrillic alphabet.", "Produces rose oil.", "Nodding means no."], shapeDescription: "Rectangular shape in the Balkans." },
  { name: "Cambodia", code: "kh", lat: 12.56, lng: 104.99, languages: ["Khmer"], facts: ["Angkor Wat temple.", "Tuk-tuks are common.", "Flag has a building."], shapeDescription: "Saucer shape in Southeast Asia." },
  { name: "Canada", code: "ca", lat: 56.13, lng: -106.34, languages: ["English", "French"], facts: ["Longest coastline.", "Most lakes in world.", "Maple syrup capital."], shapeDescription: "Massive northern landmass." },
  { name: "Chile", code: "cl", lat: -35.67, lng: -71.54, languages: ["Spanish"], facts: ["Longest country.", "Driest desert (Atacama).", "Easter Island statues."], shapeDescription: "Long thin ribbon." },
  { name: "China", code: "cn", lat: 35.86, lng: 104.19, languages: ["Chinese"], facts: ["Great Wall.", "Panda diplomacy.", "Invented paper and gunpowder."], shapeDescription: "Rooster shape." },
  { name: "Colombia", code: "co", lat: 4.57, lng: -74.29, languages: ["Spanish"], facts: ["Emeralds.", "Liquid Rainbow river.", "Coast on two oceans."], shapeDescription: "Northwest corner of South America." },
  { name: "Costa Rica", code: "cr", lat: 9.74, lng: -83.75, languages: ["Spanish"], facts: ["No army since 1949.", "Pura Vida lifestyle.", "25% protected land."], shapeDescription: "Small bridge between Nicaragua and Panama." },
  { name: "Croatia", code: "hr", lat: 45.10, lng: 15.20, languages: ["Croatian"], facts: ["Invented the tie.", "Game of Thrones filming.", "1000 islands."], shapeDescription: "Horseshoe or boomerang shape." },
  { name: "Cuba", code: "cu", lat: 21.52, lng: -77.78, languages: ["Spanish"], facts: ["Old cars.", "Cigars.", "No Coca-Cola sold officially."], shapeDescription: "Alligator shape in Caribbean." },
  { name: "Cyprus", code: "cy", lat: 35.12, lng: 33.42, languages: ["Greek", "Turkish"], facts: ["Divided capital.", "Birthplace of Aphrodite.", "Halloumi cheese."], shapeDescription: "Guitar pick shape in Mediterranean." },
  { name: "Czech Republic", code: "cz", lat: 49.81, lng: 15.47, languages: ["Czech"], facts: ["Most castles per sq mile.", "Invented contact lenses.", "Beer culture."], shapeDescription: "Oval basin surrounded by mountains." },
  { name: "Denmark", code: "dk", lat: 56.26, lng: 9.50, languages: ["Danish"], facts: ["Lego invented here.", "Oldest flag.", "Happiest country often."], shapeDescription: "Peninsula with islands like a hat." },
  { name: "Egypt", code: "eg", lat: 26.82, lng: 30.80, languages: ["Arabic"], facts: ["Pyramids.", "Nile River.", "Ancient civilization."], shapeDescription: "Square shape in North Africa." },
  { name: "Estonia", code: "ee", lat: 58.59, lng: 25.01, languages: ["Estonian"], facts: ["Digital society.", "Invented Skype.", "Kiiking is a sport."], shapeDescription: "Profile of a head facing left." },
  { name: "Ethiopia", code: "et", lat: 9.14, lng: 40.48, languages: ["Amharic"], facts: ["Never colonized.", "Coffee birthplace.", "13 months in a year."], shapeDescription: "Horn of Africa landmass." },
  { name: "Finland", code: "fi", lat: 61.92, lng: 25.74, languages: ["Finnish"], facts: ["Happiest country.", "Sauna culture.", "Heavy Metal bands."], shapeDescription: "Rabbit shape." },
  { name: "France", code: "fr", lat: 46.22, lng: 2.21, languages: ["French"], facts: ["Most visited.", "Metric system.", "Eiffel Tower."], shapeDescription: "Hexagon." },
  { name: "Germany", code: "de", lat: 51.16, lng: 10.45, languages: ["German"], facts: ["Autobahn.", "Oktoberfest.", "Bread culture."], shapeDescription: "Profile of a face looking right." },
  { name: "Greece", code: "gr", lat: 39.07, lng: 21.82, languages: ["Greek"], facts: ["Democracy.", "Philosophy.", "Islands."], shapeDescription: "Peninsula with fingers." },
  { name: "Guatemala", code: "gt", lat: 15.78, lng: -90.23, languages: ["Spanish"], facts: ["Maya civilization.", "Instant coffee invented.", "Chocolate birthplace."], shapeDescription: "Top heavy shape in Central America." },
  { name: "Hungary", code: "hu", lat: 47.16, lng: 19.50, languages: ["Hungarian"], facts: ["Rubik's cube.", "Thermal baths.", "Lake Balaton."], shapeDescription: "Kidney bean shape." },
  { name: "Iceland", code: "is", lat: 64.96, lng: -19.02, languages: ["Icelandic"], facts: ["Fire and Ice.", "No mosquitoes.", "Geothermal power."], shapeDescription: "Duck shape island." },
  { name: "India", code: "in", lat: 20.59, lng: 78.96, languages: ["Hindi", "English"], facts: ["Yoga.", "Bollywood.", "Spices."], shapeDescription: "Diamond peninsula." },
  { name: "Indonesia", code: "id", lat: -0.78, lng: 113.92, languages: ["Indonesian"], facts: ["17000 islands.", "Komodo dragons.", "Bali."], shapeDescription: "Long archipelago." },
  { name: "Iran", code: "ir", lat: 32.42, lng: 53.68, languages: ["Persian"], facts: ["Persian rugs.", "Poetry.", "Pistachios."], shapeDescription: "Snail shape." },
  { name: "Iraq", code: "iq", lat: 33.22, lng: 43.67, languages: ["Arabic"], facts: ["Cradle of Civilization.", "Mesopotamia.", "Tigris and Euphrates."], shapeDescription: "Triangular wedge." },
  { name: "Ireland", code: "ie", lat: 53.14, lng: -7.69, languages: ["English", "Irish"], facts: ["Emerald Isle.", "St Patrick.", "Guinness."], shapeDescription: "Teddy bear shape." },
  { name: "Israel", code: "il", lat: 31.04, lng: 34.85, languages: ["Hebrew"], facts: ["Dead Sea.", "Startups.", "Jerusalem."], shapeDescription: "Narrow vertical strip." },
  { name: "Italy", code: "it", lat: 41.87, lng: 12.56, languages: ["Italian"], facts: ["Roman Empire.", "Pizza.", "Renaissance."], shapeDescription: "Boot shape." },
  { name: "Jamaica", code: "jm", lat: 18.10, lng: -77.29, languages: ["English"], facts: ["Reggae.", "Usain Bolt.", "Blue Mountain Coffee."], shapeDescription: "Swimming turtle." },
  { name: "Japan", code: "jp", lat: 36.20, lng: 138.25, languages: ["Japanese"], facts: ["Sushi.", "Anime.", "Bullet trains."], shapeDescription: "Seahorse shape." },
  { name: "Jordan", code: "jo", lat: 30.58, lng: 36.23, languages: ["Arabic"], facts: ["Petra.", "Dead Sea.", "Wadi Rum."], shapeDescription: "Hatchet shape." },
  { name: "Kenya", code: "ke", lat: -0.02, lng: 37.90, languages: ["Swahili"], facts: ["Safari.", "Runners.", "Maasai."], shapeDescription: "Diamond shape in East Africa." },
  { name: "Latvia", code: "lv", lat: 56.87, lng: 24.60, languages: ["Latvian"], facts: ["Amber coast.", "Wide waterfalls.", "Internet speed."], shapeDescription: "Horizontal block in Baltics." },
  { name: "Lithuania", code: "lt", lat: 55.16, lng: 23.88, languages: ["Lithuanian"], facts: ["Basketball.", "Hill of Crosses.", "Center of Europe."], shapeDescription: "Round blob in Baltics." },
  { name: "Madagascar", code: "mg", lat: -18.76, lng: 46.86, languages: ["Malagasy"], facts: ["Lemurs.", "Baobabs.", "Vanilla."], shapeDescription: "Large footprint island." },
  { name: "Malaysia", code: "my", lat: 4.21, lng: 101.97, languages: ["Malay"], facts: ["Petronas Towers.", "Orangutans.", "Two parts."], shapeDescription: "Split country." },
  { name: "Mexico", code: "mx", lat: 23.63, lng: -102.55, languages: ["Spanish"], facts: ["Tacos.", "Aztecs.", "Day of the Dead."], shapeDescription: "Funnel shape." },
  { name: "Mongolia", code: "mn", lat: 46.86, lng: 103.84, languages: ["Mongolian"], facts: ["Genghis Khan.", "Horses.", "Nomads."], shapeDescription: "Oval shape." },
  { name: "Morocco", code: "ma", lat: 31.79, lng: -7.09, languages: ["Arabic"], facts: ["Blue city.", "Souks.", "Sahara."], shapeDescription: "Northwest corner of Africa." },
  { name: "Nepal", code: "np", lat: 28.39, lng: 84.12, languages: ["Nepali"], facts: ["Everest.", "Sherpas.", "Non-rectangular flag."], shapeDescription: "Rectangle." },
  { name: "Netherlands", code: "nl", lat: 52.13, lng: 5.29, languages: ["Dutch"], facts: ["Windmills.", "Tulips.", "Bikes."], shapeDescription: "River delta." },
  { name: "New Zealand", code: "nz", lat: -40.90, lng: 174.88, languages: ["English"], facts: ["Kiwis.", "Rugby.", "Hobbits."], shapeDescription: "Two islands." },
  { name: "Nigeria", code: "ng", lat: 9.08, lng: 8.67, languages: ["English"], facts: ["Nollywood.", "Oil.", "Jollof rice."], shapeDescription: "Square shape." },
  { name: "North Korea", code: "kp", lat: 40.33, lng: 127.51, languages: ["Korean"], facts: ["Hermit Kingdom.", "Kim dynasty.", "Mass games."], shapeDescription: "Top of peninsula." },
  { name: "Norway", code: "no", lat: 60.47, lng: 8.46, languages: ["Norwegian"], facts: ["Fjords.", "Vikings.", "Oil fund."], shapeDescription: "Spoon shape." },
  { name: "Pakistan", code: "pk", lat: 30.37, lng: 69.34, languages: ["Urdu"], facts: ["K2.", "Cricket.", "Truck art."], shapeDescription: "Dinosaur head." },
  { name: "Panama", code: "pa", lat: 8.53, lng: -80.78, languages: ["Spanish"], facts: ["Canal.", "Hats.", "Biomuseo."], shapeDescription: "S-shape connector." },
  { name: "Peru", code: "pe", lat: -9.18, lng: -75.01, languages: ["Spanish"], facts: ["Machu Picchu.", "Llamas.", "Potatoes."], shapeDescription: "Vertical strip." },
  { name: "Philippines", code: "ph", lat: 12.87, lng: 121.77, languages: ["English", "Filipino"], facts: ["7000 islands.", "Jeepneys.", "Boxers."], shapeDescription: "Sitting dog." },
  { name: "Poland", code: "pl", lat: 51.91, lng: 19.14, languages: ["Polish"], facts: ["Pierogi.", "Pope John Paul II.", "Witcher."], shapeDescription: "Round." },
  { name: "Portugal", code: "pt", lat: 39.39, lng: -8.22, languages: ["Portuguese"], facts: ["Cork.", "Explorers.", "Tiles."], shapeDescription: "Face profile." },
  { name: "Romania", code: "ro", lat: 45.94, lng: 24.96, languages: ["Romanian"], facts: ["Dracula.", "Parliament.", "Danube Delta."], shapeDescription: "Fish shape." },
  { name: "Russia", code: "ru", lat: 61.52, lng: 105.31, languages: ["Russian"], facts: ["Largest.", "Vodka.", "Ballet."], shapeDescription: "Bear shape." },
  { name: "Saudi Arabia", code: "sa", lat: 23.88, lng: 45.07, languages: ["Arabic"], facts: ["Mecca.", "Oil.", "Desert."], shapeDescription: "Large boot." },
  { name: "Singapore", code: "sg", lat: 1.35, lng: 103.81, languages: ["English"], facts: ["Lion City.", "Clean.", "Garden city."], shapeDescription: "Diamond." },
  { name: "South Africa", code: "za", lat: -30.55, lng: 22.93, languages: ["English"], facts: ["Rainbow nation.", "Mandela.", "Safari."], shapeDescription: "Tip of Africa." },
  { name: "South Korea", code: "kr", lat: 35.90, lng: 127.76, languages: ["Korean"], facts: ["K-Pop.", "Kimchi.", "Tech."], shapeDescription: "Bottom of peninsula." },
  { name: "Spain", code: "es", lat: 40.46, lng: -3.74, languages: ["Spanish"], facts: ["Paella.", "Siesta.", "Flamenco."], shapeDescription: "Bull skin." },
  { name: "Sri Lanka", code: "lk", lat: 7.87, lng: 80.77, languages: ["Sinhala", "Tamil"], facts: ["Tea.", "Cinnamon.", "Pearl of Indian Ocean."], shapeDescription: "Teardrop." },
  { name: "Sweden", code: "se", lat: 60.12, lng: 18.64, languages: ["Swedish"], facts: ["IKEA.", "ABBA.", "Fika."], shapeDescription: "Long strip." },
  { name: "Switzerland", code: "ch", lat: 46.81, lng: 8.22, languages: ["German"], facts: ["Watches.", "Chocolate.", "Neutral."], shapeDescription: "Pig shape." },
  { name: "Taiwan", code: "tw", lat: 23.69, lng: 120.96, languages: ["Chinese"], facts: ["Bubble tea.", "Chips.", "Night markets."], shapeDescription: "Sweet potato." },
  { name: "Thailand", code: "th", lat: 15.87, lng: 100.99, languages: ["Thai"], facts: ["Smiles.", "Street food.", "Elephants."], shapeDescription: "Elephant head." },
  { name: "Turkey", code: "tr", lat: 38.96, lng: 35.24, languages: ["Turkish"], facts: ["Istanbul.", "Kebabs.", "Carpets."], shapeDescription: "Rectangle." },
  { name: "Uganda", code: "ug", lat: 1.37, lng: 32.29, languages: ["English", "Swahili"], facts: ["Source of the Nile.", "Gorillas.", "Rolex (food)."], shapeDescription: "Boxy shape near Lake Victoria." },
  { name: "Ukraine", code: "ua", lat: 48.37, lng: 31.16, languages: ["Ukrainian"], facts: ["Sunflower oil.", "Chernobyl.", "Breadbasket."], shapeDescription: "Wide block." },
  { name: "United Arab Emirates", code: "ae", lat: 23.42, lng: 53.84, languages: ["Arabic"], facts: ["Burj Khalifa.", "Dubai.", "Expats."], shapeDescription: "Hook shape." },
  { name: "United Kingdom", code: "gb", lat: 55.37, lng: -3.43, languages: ["English"], facts: ["Royals.", "Tea.", "Shakespeare."], shapeDescription: "Rabbit shape." },
  { name: "United States", code: "us", lat: 37.09, lng: -95.71, languages: ["English"], facts: ["Hollywood.", "Moon landing.", "Burgers."], shapeDescription: "Wide rectangle." },
  { name: "Uruguay", code: "uy", lat: -32.52, lng: -55.76, languages: ["Spanish"], facts: ["First World Cup host.", "Mate tea.", "Most cows per person."], shapeDescription: "Rounded wedge." },
  { name: "Uzbekistan", code: "uz", lat: 41.37, lng: 64.58, languages: ["Uzbek"], facts: ["Double landlocked.", "Silk Road.", "Samarkand."], shapeDescription: "Horizontal strip." },
  { name: "Vatican City", code: "va", lat: 41.90, lng: 12.45, languages: ["Italian", "Latin"], facts: ["Smallest country.", "Pope's home.", "No army."], shapeDescription: "Tiny enclave." },
  { name: "Venezuela", code: "ve", lat: 6.42, lng: -66.58, languages: ["Spanish"], facts: ["Angel Falls.", "Oil.", "Arepas."], shapeDescription: "Rhino head." },
  { name: "Vietnam", code: "vn", lat: 14.05, lng: 108.27, languages: ["Vietnamese"], facts: ["Coffee.", "Pho.", "Motorbikes."], shapeDescription: "S-shape." },
  { name: "Yemen", code: "ye", lat: 15.55, lng: 48.51, languages: ["Arabic"], facts: ["Coffee mocha.", "Dragon Blood Trees.", "Old skyscrapers."], shapeDescription: "Heel of the boot." },
  { name: "Zambia", code: "zm", lat: -13.13, lng: 27.84, languages: ["English"], facts: ["Victoria Falls.", "Copper.", "Walking safari."], shapeDescription: "Butterfly shape." },
  { name: "Zimbabwe", code: "zw", lat: -19.01, lng: 29.15, languages: ["English"], facts: ["Great Zimbabwe ruins.", "Victoria Falls.", "Inflation history."], shapeDescription: "Teapot shape." }
];
